branches:
  only:
  - master
language: android
jdk: oraclejdk7
env:
  global:
  - secure: PpcvmeijzW8Hm9GbLveIRyPXAYRoZIMIFYe+mQk3CCzO1CJU1TJPf/MLLmHsKavVFdBbgiiqijNwfxaE1kpvITryZm9+dpJ7B5xA8IQYV1vJw74bguNWNtGU4KXHBW4ALy54rKkuki6DCAZl2ZmSlDLQGFxw5BmFZJlQIhgDg1k=
  - secure: TJfoJvz3AhR20Zi4GqZAXAR9HHFKGV/Y+8wpI8+rkE+f2946OcxLXgFoEw6XBWaf3JZ6+/XJ+SdSFoNsERp4+mPd8TCAYBCIhSC1Ma9MVg82F7+482UuPM8ShGRzOwf/dEZx4EMCiosbnfYYgNSUdlnYnBl6zlIUSaqFYG2nUno=
android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - android-22
  - build-tools-22.0.1
install:
- "./gradlew dependencies"
script:
- "./gradlew build"
after_success:
- "./gradlew uploadArchives"
